### ISSUE TITLE
tensorflow import?

### ISSUE THREAD

**Issue by MiroFurtado** [vpj/lab#2]
I don't think the `tensorflow` import in the `experiments.pytorch` file is necessary - you can write to `tensorboard` without tensorflow.

Indeed, some of your usages are actually deprecated.

**Comment by vpj** [comment]
I'm sorry I wasn't aware. Can you please point me to some examples or documentation regarding that. Thanks

**Comment by vpj** [comment]
Was using TensorFlow 1.13, fill migrate to the new api.
