### ISSUE TITLE
Support for TF 2.0

### ISSUE THREAD

**Issue by janithwanni** [vpj/lab#3]
The previous issue  #2 suggested that migration to the TensorFlow 2.0 API was underway. Has it being completed? or is there room to work on that at the moment.  

Thanks.

**Comment by vpj** [comment]
No I haven't worked on it.

We are working on a new version with some breaking changes to the API. So I don't think we'll be able to add TF 2.0 support to current version. Great if you can work on adding TF 2.0 support. Thanks.
